// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_PTy8OPWvKCAHNCntEkCVg6JJlvrrbE',
    appId: '1:270007385408:web:bf82e67869293eb4570ea5',
    messagingSenderId: '270007385408',
    projectId: 'organix-898be',
    authDomain: 'organix-898be.firebaseapp.com',
    storageBucket: 'organix-898be.appspot.com',
    measurementId: 'G-X4E00WV895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoO9rxApp6xVTRCPRG07oiwhR5cUIPao',
    appId: '1:270007385408:android:509da115e4b57ed6570ea5',
    messagingSenderId: '270007385408',
    projectId: 'organix-898be',
    storageBucket: 'organix-898be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQOH0zm0bJ4SgyXo6BW3qB3vGAHZs3Zs',
    appId: '1:270007385408:ios:a14072c4a4f0d21c570ea5',
    messagingSenderId: '270007385408',
    projectId: 'organix-898be',
    storageBucket: 'organix-898be.appspot.com',
    iosBundleId: 'com.example.organix',
  );
}
